#!/usr/bin/env bash

echo "Starting deploy script..."
cd ONSdigital/es-helloworld
echo "In project directory"
git checkout master
echo "Checked out Github master branch"
git remote add -v algo https://git.algorithmia.com/git/awharris/helloworld.git
echo "Added remote to Algorithmia Git repository"
git pull algo master
echo "Pulled Algorithmia master branch"
git push algo master
echo "Pushed changes to Algorithmia master branch"
