#!/usr/bin/env bash

echo "Starting deploy script..."
git checkout master
echo "Checked out Github master branch"
git remote add algo https://${algo_user}:${algo_password}@git.algpoc.com/git/harria1/helloworld.git
echo "Added remote to Algorithmia Git repository"
git pull algo master --allow-unrelated-histories
echo "Pulled Algorithmia master branch"
git push algo master
echo "Pushed changes to Algorithmia master branch"
